name: release
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set TAG and VERSION
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          TAG="${TAG#v}"   # strip leading v if present

          # VERSION=6.16 for 6.16.y, otherwise keep full tag (e.g. 6.16.2)
          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.y$ ]]; then
            VERSION="${TAG%.y}"
          else
            VERSION="$TAG"
          fi

          echo "TAG=$TAG" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "CPU_ARCH=$(uname -m)" >> "$GITHUB_ENV"

      - name: Build
        run: |
          ./build.sh $TAG
          sha256sum linux-stable/vmlinux-${{ env.VERSION }}.${{ env.CPU_ARCH }} > linux-stable/vmlinux-${{ env.VERSION }}.${{ env.CPU_ARCH }}.sha256

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux-stable/vmlinux-${{ env.VERSION }}.${{ env.CPU_ARCH }}
            linux-stable/vmlinux-${{ env.VERSION }}.${{ env.CPU_ARCH }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
