name: release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish"
        type: "string"
        required: true

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set TAG and VERSION
        run: |
          TAG="${{ github.event.inputs.tag || github.ref_name }}"
          VERSION="${TAG%.y}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build
        run: |
          ./build.sh $TAG
          sha256 linux-stable/vmlinux-${{ env.VERSION }} > linux-stable/vmlinux-${{ env.VERSION }}.sha256

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux-stable/vmlinux-${{ env.VERSION }}
            linux-stable/vmlinux-${{ env.VERSION }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
